import { API_CONFIG } from '@/core/config/api.config';

export const USER_TYPE_CONFIG: Record<string, any> = {
  SUPER_ADMIN: {
    title: 'Super Admins',
    endpoint: API_CONFIG.ENDPOINTS.USERS.BASE,
    userType: API_CONFIG.ENDPOINTS.USERS.TYPE.SUPER_ADMIN,
    entityLabel: 'Super Admin',
    columns: [
      { field: 'name', header: 'Name', sortable: true },
      { field: 'email', header: 'Email', sortable: true },
      { field: 'phone_number', header: 'Phone number', sortable: true },
      { field: 'categories', header: 'Division', sortable: true },
      { field: 'updated_at', header: 'Last Update', sortable: true, type: 'date' },
      { field: 'updated_by', header: 'Updated By', sortable: true },
      { field: 'is_active', header: 'Actions', type: 'toggle', customClass: 'justify-end' },
    ],
    entityEndpoint: API_CONFIG.ENDPOINTS.DIVISIONS,
    navPath: '/dashboard/super-admin-users',
    dependencies: ['generalDivisions'],
  },
  AUTHORITY: {
    title: 'Authority Users',
    endpoint: API_CONFIG.ENDPOINTS.USERS.BASE,
    userType: API_CONFIG.ENDPOINTS.USERS.TYPE.AUTHORITY,
    entityLabel: 'User',
    columns: [
      { field: 'name', header: 'Username', sortable: true },
      { field: 'email', header: 'Email', sortable: true },
      { field: 'phone_number', header: 'Phone', sortable: true },
      { field: 'authority', header: 'Authority', sortable: true },
      { field: 'categories', header: 'Division', sortable: true },
      { field: 'updated_at', header: 'Last Update', sortable: true, type: 'date' },
      { field: 'updated_by', header: 'Updated By', sortable: true },
      { field: 'is_active', header: 'Actions', type: 'toggle', customClass: 'justify-end' },
    ],
    entityEndpoint: API_CONFIG.ENDPOINTS.ENTITIES.BASE,
    entityType: API_CONFIG.ENDPOINTS.ENTITIES.TYPE.AUTHORITY,
    navPath: '/dashboard/authorities-users',
    dependencies: ['authorities', 'generalDivisions'],
  },
  GOVERNORATES: {
    title: 'Governorate Users',
    endpoint: API_CONFIG.ENDPOINTS.USERS.BASE,
    userType: API_CONFIG.ENDPOINTS.USERS.TYPE.GOVERNORATES,
    entityLabel: 'User',
    columns: [
      { field: 'name', header: 'Name', sortable: true },
      { field: 'email', header: 'Email', sortable: true },
      { field: 'phone_number', header: 'Phone Number', sortable: true },
      { field: 'directorate', header: 'Directorate', sortable: true },
      { field: 'categories', header: 'Division', sortable: true },
      { field: 'updated_at', header: 'Last Update', sortable: true, type: 'date' },
      { field: 'updated_by', header: 'Updated By', sortable: true },
      { field: 'is_active', header: 'Actions', type: 'toggle', customClass: 'justify-end' },
    ],
    entityEndpoint: API_CONFIG.ENDPOINTS.ENTITIES.BASE,
    entityType: API_CONFIG.ENDPOINTS.ENTITIES.TYPE.GOVERNORATES,
    navPath: '/dashboard/governorates-users',
    dependencies: ['directorates', 'generalDivisions'],
  },
  SECTORS: {
    title: 'Sector Users',
    endpoint: API_CONFIG.ENDPOINTS.USERS.BASE,
    userType: API_CONFIG.ENDPOINTS.USERS.TYPE.SECTORS,
    entityLabel: 'User',
    columns: [
      { field: 'name', header: 'Name', sortable: true },
      { field: 'email', header: 'Email', sortable: true },
      { field: 'phone_number', header: 'Phone Number', sortable: true },
      { field: 'directorate', header: 'Directorate', sortable: true },
      { field: 'division', header: 'Health Division', sortable: true },
      { field: 'categories', header: 'Division', sortable: true },
      { field: 'updated_at', header: 'Last Update', sortable: true, type: 'date' },
      { field: 'updated_by', header: 'Updated By', sortable: true },
      { field: 'is_active', header: 'Actions', type: 'toggle', customClass: 'justify-end' },
    ],
    entityEndpoint: API_CONFIG.ENDPOINTS.ENTITIES.BASE,
    entityType: API_CONFIG.ENDPOINTS.ENTITIES.TYPE.SECTORS,
    navPath: '/dashboard/sectors-users',
    dependencies: ['directorates', 'healthDivisions', 'generalDivisions'],
  },
  FACILITIES: {
    title: "Authority's Hospital Users",
    endpoint: API_CONFIG.ENDPOINTS.USERS.BASE,
    userType: API_CONFIG.ENDPOINTS.USERS.TYPE.FACILITIES,
    entityLabel: 'User',
    columns: [
      { field: 'name', header: 'Username', sortable: true },
      { field: 'email', header: 'Email', sortable: true },
      { field: 'phone_number', header: 'Phone', sortable: true },
      { field: 'authority', header: 'Authority', sortable: true },
      { field: 'hospital', header: 'Hospital', sortable: true },
      { field: 'categories', header: 'Division', sortable: true },
      { field: 'updated_at', header: 'Last Update', sortable: true, type: 'date' },
      { field: 'updated_by', header: 'Updated By', sortable: true },
      { field: 'is_active', header: 'Actions', type: 'toggle', customClass: 'justify-end' },
    ],
    entityEndpoint: API_CONFIG.ENDPOINTS.ENTITIES.BASE,
    entityType: API_CONFIG.ENDPOINTS.ENTITIES.TYPE.FACILITIES,
    navPath: '/dashboard/facilities-users',
    dependencies: ['authorities', 'hospitals', 'generalDivisions'],
  },
};
