import { API_CONFIG } from '@/core/config/api.config';
import { Validators } from '@angular/forms';

export const ENTITY_TYPE_CONFIG: Record<string, any> = {
  DIVISION: {
    title: 'Divisions',
    entityLabel: 'Division',
    endpoint: API_CONFIG.ENDPOINTS.CATEGORIES,
    navPath: '/dashboard/divisions',
    columns: [
      { field: 'name', header: 'Name', sortable: true },
      { field: 'updated_at', header: 'Last Update', sortable: true, type: 'date' },
      { field: 'updated_by', header: 'Updated By', sortable: true },
      { field: 'is_active', header: 'Actions', type: 'toggle', customClass: 'justify-end' },
    ],
    formFields: (deps: any) => [
      {
        key: 'name',
        label: 'Division Name',
        type: 'text',
        placeholder: 'Enter division name...',
        validators: [Validators.required],
        colSpan: 'col-span-1',
      },
      {
        key: 'authority_id',
        label: 'Authority Name',
        type: 'select',
        placeholder: 'Select authority name...',
        options: deps.authorities || [],
        validators: [Validators.required],
        roles: ['ministry'],
        colSpan: 'col-span-1',
        filter: true,
        virtualScroll: true,
        loading: deps.isAuthoritiesLoading,
      },
    ],
  },
  GOVERNORATES: {
    title: 'Governorates',
    entityLabel: 'Governorate',
    endpoint: API_CONFIG.ENDPOINTS.ENTITIES.BASE,
    entity_type: API_CONFIG.ENDPOINTS.ENTITIES.TYPE.GOVERNORATES,
    navPath: '/dashboard/governorates',
    columns: [
      { field: 'name', header: 'Name', sortable: true },
      { field: 'updated_at', header: 'Last Update', sortable: true, type: 'date' },
      { field: 'updated_by', header: 'Updated By', sortable: true },
      { field: 'is_active', header: 'Actions', type: 'toggle', customClass: 'justify-end' },
    ],
    formFields: (deps: any) => [
      {
        key: 'name',
        label: 'Governorate Name',
        type: 'text',
        placeholder: 'Enter Governorate name...',
        validators: [Validators.required],
        colSpan: 'col-span-1',
      },
      {
        key: 'authority_id',
        label: 'Authority Name',
        type: 'select',
        placeholder: 'Select authority name...',
        options: deps.authorities || [],
        validators: [Validators.required],
        roles: ['ministry'],
        colSpan: 'col-span-1',
        filter: true,
        virtualScroll: true,
        loading: deps.isAuthoritiesLoading,
      },
    ],
  },
  SECTORS: {
    title: 'Sectors',
    entityLabel: 'Sector',
    endpoint: API_CONFIG.ENDPOINTS.ENTITIES.BASE,
    entity_type: API_CONFIG.ENDPOINTS.ENTITIES.TYPE.SECTORS,
    navPath: '/dashboard/sectors',
    columns: [
      { field: 'name', header: 'Name', sortable: true },
      { field: 'directorate', header: 'Directorate', sortable: true, type: 'text' },
      { field: 'updated_at', header: 'Last Update', sortable: true, type: 'date' },
      { field: 'updated_by', header: 'Updated By', sortable: true },
      { field: 'is_active', header: 'Actions', type: 'toggle', customClass: 'justify-end' },
    ],
    formFields: (deps: any) => [
      {
        key: 'name',
        label: 'Sector Name',
        type: 'text',
        placeholder: 'Enter sector name...',
        validators: [Validators.required],
        colSpan: 'col-span-1',
      },
      {
        key: 'health_directorate_id',
        label: 'Governorate',
        type: 'multiselect',
        placeholder: 'Select Governorate...',
        options: deps.directorates || [],
        validators: [Validators.required],
        colSpan: 'col-span-1',
        filter: true,
        virtualScroll: true,
        loading: deps.isDirectoratesLoading,
      },
      {
        key: 'authority_id',
        label: 'Authority Name',
        type: 'select',
        placeholder: 'Select authority name...',
        options: deps.authorities || [],
        validators: [Validators.required],
        roles: ['ministry'],
        colSpan: 'col-span-1',
        filter: true,
        virtualScroll: true,
        loading: deps.isAuthoritiesLoading,
      },
    ],
  },
  AUTHORITY: {
    title: 'Authorities',
    entityLabel: 'Authority',
    endpoint: API_CONFIG.ENDPOINTS.ENTITIES.BASE,
    entity_type: API_CONFIG.ENDPOINTS.ENTITIES.TYPE.AUTHORITY,
    navPath: '/dashboard/authorities',
    columns: [
      { field: 'name', header: 'Name', sortable: true },
      { field: 'updated_at', header: 'Last Update', sortable: true, type: 'date' },
      { field: 'updated_by', header: 'Updated By', sortable: true },
      { field: 'is_active', header: 'Actions', type: 'toggle', customClass: 'justify-end' },
    ],
    formFields: () => [
      {
        key: 'name',
        label: 'Authority Name',
        type: 'text',
        placeholder: 'Enter authority name',
        validators: [Validators.required],
        colSpan: 'col-span-full',
      },
      {
        key: 'image',
        label: 'Authority Logo',
        type: 'image',
        colSpan: 'col-span-full',
      },
    ],
  },
  FACILITIES: {
    title: 'Facilities',
    entityLabel: 'Facility',
    endpoint: API_CONFIG.ENDPOINTS.ENTITIES.BASE,
    entity_type: API_CONFIG.ENDPOINTS.ENTITIES.TYPE.FACILITIES,
    parent_type: API_CONFIG.ENDPOINTS.ENTITIES.TYPE.AUTHORITY,
    navPath: '/dashboard/facilities',
    columns: [
      { field: 'name', header: 'Name', sortable: true },
      { field: 'authority', header: 'Authority', sortable: true, type: 'text' },
      { field: 'categories', header: 'Division', sortable: true, type: 'text' },
      { field: 'updated_at', header: 'Last Update', sortable: true, type: 'date' },
      { field: 'updated_by', header: 'Updated By', sortable: true },
      { field: 'is_active', header: 'Actions', type: 'toggle', customClass: 'justify-end' },
    ],
    formFields: (deps: any) => [
      {
        key: 'name',
        label: 'Hospital Authority Name',
        type: 'text',
        placeholder: 'Enter hospital authority name...',
        validators: [Validators.required],
        colSpan: 'col-span-1',
      },
      {
        key: 'category_ids',
        label: 'Divison Name',
        type: 'multiselect',
        placeholder: 'Select Division name...',
        options: deps.generalDivisions || [],
        validators: [],
        colSpan: 'col-span-1',
        virtualScroll: true,
        filter: true,
        loading: deps.isGeneralDivisionsLoading,
      },
      {
        key: 'authority_id',
        label: 'Authority',
        type: 'select',
        placeholder: 'Select authority...',
        options: deps.authorities || [],
        validators: [Validators.required],
        colSpan: 'col-span-1',
        roles: ['ministry'],
        filter: true,
        virtualScroll: true,
        loading: deps.isAuthoritiesLoading,
      },
      {
        key: 'authority_id',
        label: 'Sector',
        type: 'multiselect',
        placeholder: 'Select Sector',
        options: deps.authorities || [],
        validators: [Validators.required],
        colSpan: 'col-span-1',
        filter: true,
        virtualScroll: true,
        loading: deps.isAuthoritiesLoading,
      },
      {
        key: 'health_directorate_id',
        label: 'Governorate',
        type: 'multiselect',
        placeholder: 'Select Governorate...',
        options: deps.directorates || [],
        validators: [Validators.required],
        colSpan: 'col-span-1',
        filter: true,
        virtualScroll: true,
        loading: deps.isDirectoratesLoading,
      },
    ],
    dependencies: ['authorities', 'generalDivisions'],
  },
  NOT_FOUND: {
    title: 'Not Found',
    entityLabel: 'Entity',
    endpoint: '',
    navPath: '/',
    columns: [],
    formFields: () => [],
  },
};
